/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Khumo
 */
public class RemoveFrame extends javax.swing.JFrame {
 ArrayList<Tasks> tasks;
 Addition adding;
    /**
     * Creates new form RemoveFrame
     */
    public RemoveFrame() {
        initComponents();
         adding = new Addition();
       tasks=adding.sendTask();
        adding.loadTasksFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select the Task that you want to remove");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Name of Task");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /*  try{
          File file = new File("UserInfo.txt");
           Scanner scanner = new Scanner(file);
           
            ArrayList<String> lines = new ArrayList<>();

            // Read the file into a list of strings
            int i =0;
              while (i < tasks.size()) {
                String line = tasks.get(i).getTaskName()+" "+tasks.get(i).getTaskPriority()+" "+tasks.get(i).getTaskStatus()+" "+tasks.get(i).getDaysRemaining();
            

                // Check if this line represents the task to delete
                if ( (tasks.get(i).getTaskName().equalsIgnoreCase(jTextField1.getText()))){
                    lines.add(line);
                }else{
                
                 lines.add(line);
                }
                i++;
            }
              
               scanner.close();

            // Write the updated list back to the file
            FileWriter writer = new FileWriter("UserInfo.txt");
            for (String line : lines) {
                writer.write(line + System.lineSeparator());
            }
            writer.close();
              
        }catch(FileNotFoundException e){
         JOptionPane.showMessageDialog(null, "File not found.");
        
        } catch(IOException e){
        
               JOptionPane.showMessageDialog(null, "Error reading or writing to file");
        }*/
      
          try {
        File file = new File("UserInfo.txt");
        Scanner scanner = new Scanner(file);

        ArrayList<String> lines = new ArrayList<>();

        // Read and prepare lines to write, skipping the task to remove
        String taskToRemove = jTextField1.getText().trim().toLowerCase();
        boolean taskFound = false;

        for (Tasks task : tasks) {
            String taskName = task.getTaskName().trim().toLowerCase();
            String line = task.getTaskName() + " " + task.getTaskPriority() + " " + task.getTaskStatus() + " " + task.getDaysRemaining();

            if (taskName.equals(taskToRemove)) {
                taskFound = true; // found the task, skip it
                continue;
            }
            lines.add(line); // add all other tasks
        }

        scanner.close();

        if (taskFound) {
            FileWriter writer = new FileWriter("UserInfo.txt");
            for (String line : lines) {
                writer.write(line + System.lineSeparator());
            }
            writer.close();
            JOptionPane.showMessageDialog(null, "Task removed successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Task not found.");
        }

    } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(null, "File not found.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error reading or writing to file.");
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
